### ISSUE TITLE
please publish module to npm

### ISSUE THREAD

**Issue by bcoe** [Sneagan/atom-handlebars#18]
Could you please publish the handlebars module to npm? We are using the same highlighting engine as Atom now, and would like to add your grammar:

https://www.npmjs.com/package/polyglot-readme

**Comment by Sneagan** [comment]
Will do. This month will be a good opportunity for me to get back in the saddle on my open source work (finally).

**Comment by Sneagan** [comment]
Done! https://www.npmjs.com/package/atom-handlebars
