### ISSUE TITLE
Store package settings files in the `settings/` directory instead of `scoped-properties/`

### ISSUE THREAD

**Issue by benogle** [Sneagan/atom-handlebars#19]
Reported via deprecation-cop

**Comment by Sneagan** [comment]
Thanks for adding this! Merged a fix. :)

**Comment by yiliang** [comment]
Hi @Sneagan I've got the same issue with the package language-slim. Could you look into it?
![screenshot](https://cloud.githubusercontent.com/assets/1404615/7289706/5625bbfc-e9a6-11e4-9d37-c65416d6167c.png)

**Comment by Sneagan** [comment]
@yiliangt This looks like an issue with this package, not mine. https://github.com/slim-template/language-slim

**Comment by yiliangt** [comment]
@Sneagan. Ok thanks.
