### ISSUE TITLE
Atom doesn't color text properly when there is a forward slash in the name

### ISSUE THREAD

**Issue by adam-knights** [Sneagan/atom-handlebars#34]
To reproduce:

Create a new test.hbs file with the following two lines:

    {{forms-colors-nicely name="priceManualSwitch" checked=manualPriceChecked}}
    {{forms/colors-nicely name="priceManualSwitch" checked=manualPriceChecked}}

The second line remains all grey (apart from the {{ and }}) whereas 'name' and 'checked' change to orange on line 1 and "priceManualSwitch" to green.

![handlebars-grey](https://cloud.githubusercontent.com/assets/12710362/9200843/bec83fd0-4041-11e5-9b39-eeca07597679.png)

It appears that the / in the component name stops the nice coloring. The / is used in Ember in particular from about version 1.10 to 1.13 to organise components into sub folders.

Atom Version 1.0.5, Windows 7 64bit
atom-handlebars version 1.1.0

**Comment by adam-knights** [comment]
Fixed by https://github.com/Sneagan/atom-handlebars/pull/33

**Comment by Sneagan** [comment]
Thanks!
